config/routes.rb
Meetme::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  resources :avatars, only: [:edit, :update, :destroy]

  post    'meetups/:meetup_id/attend' => 'attends#create', as: 'attend_meetup'
  delete 'meetups/:meetup_id/attend' => 'attends#destroy'

  get  'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get  'logout' => 'sessions#destroy', as: 'logout'

  get  'register' => 'users#new', as: 'register'
  post  'register' => 'users#create'

  root 'home#index'

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base

  has_and_belongs_to_many :users, join_table: 'attends'
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  authorize_resource only: [:new, :show, :edit, :update, :destroy]
  before_filter :meetup, only: [:show, :edit, :update, :destroy]
  helper_method :meetup

  def index
    @meetups = Meetup.all
  end

  def new
    @meetup = Meetup.new
  end

  def create
    @meetup = Meetup.new meetup_params
    if @meetup.save
      flash[:succes] = "Successfully created a meetup"
      redirect_to meetups_path
    else
      flash[:error] = "Couldn't create a meetup"
      render :new 
    end
  end

  def show
  end

  def edit
  end

  def update  
    if @meetup.update_attributes(meetup_params)
      flash[:succes] = "Update successfully a meetup"
      redirect_to meetups_path
    else
      flash[:error] = "Couldn't update a meetup"
      render :new 
    end
  end

  def destroy
    @meetup.destroy
    flash[:succes] = "Successfully deleted a meetup"
    redirect_to meetups_path
  end

  def meetup_params
    params.require(:meetup).permit(:name, :description, :address, :city, :state, :zip, :start_at, :ends_at)
  end

  private

  def meetup
    @meetup ||= Meetup.find params[:id]
  end
end

app/views/meetups/_attend.html.erb
<div class="well">
	<% if current_user && current_user.attends_for_meetup?(meetup) %>	
		<p> You're going to this meetup! </p>
		<p> <%= link_to 'Cancel', attend_meetup_path(meetup), class: 'btn btn-danger', method: 'delete' %>
	<% else %>
		<p> Would you like to attend this meetup? </p>
		<p> <%= link_to "Attend for this mettup", attend_meetup_path(meetup), class: 'btn btn-success', method: 'post' %>
	<% end %>
</div>

app/views/meetups/_form.html.erb
<fieldset>
  <%= form_for @meetup do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :address %>
      <%= f.text_field :address %>
    </p>
    <p>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </p>
    <p>
      <%= f.label :state %>
      <%= f.text_field :state %>
    </p>
    <p>
      <%= f.label :zip %>
      <%= f.text_field :zip %>
    </p>
    <p>
      <%= f.label :start_at %>
      <%= f.text_field :start_at %>
    </p>
    <p>
      <%= f.label :ends_at %>
      <%= f.text_field :ends_at %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>

    <p class="actions">
      <%= f.submit class: 'btn btn-primary'  %>
      <%= link_to 'Cancel', meetups_path, class: 'btn' %>
    </p>
  <% end %>
</fieldset>

app/views/meetups/_meetup.html.erb
<section class="meetups well">
<h2> <%= meetup.name %> </h2>

<h3> Location </h3>
<%= meetup.address %>
<%= "#{meetup.city} #{meetup.state} #{meetup.zip}" %>

<h3> Date and hour </h3>
<p> <strong> Start at </strong> <%= meetup.start_at %> </p>
<p> <strong> Ends at </strong> <%= meetup.ends_at %> </p>

<h3> Description </h3>
<%= meetup.description %>

<div class="attend-info">
	<%= render :partial => 'attend', locals: { meetup: meetup} %>
</div>

<% if can? :manage, meetup %>
<p class="actions">
	<%= link_to "Show", meetup_path(meetup), class: 'btn btn-primary' %>
	<%= link_to "Delete", meetup, class: 'btn btn-danger', confirm: "Are you sure? ", method: 'delete' %>
</p>
<% end %>


</section>	

app/views/meetups/edit.html.erb
<h1>Edit Meetup</h1>

<%= render 'form' %>

app/views/meetups/index.html.erb
<div class="meetups">
	<% if @meetups.present? %>
		<%= render @meetups %>
	<% else %>
		<p> Sorry! There are no meetups at the moment </p>
	<% end %> 
	<% if can? :manage, Meetup.new %>
	<p class='actions'>
		<%= link_to 'Add new meetup', new_meetup_path, class: 'btn btn-primary' %>
	</p>
	<% end %>
</div>

app/views/meetups/new.html.erb
<h1>New Meetup</h1>

<%= render 'form' %>

app/views/meetups/show.html.erb
<section class="meetups">
<h2><%= meetup.name %></h2>
<hr>
<article class="well">
<h3>Location</h3>

<%= meetup.address %>
<%= "#{meetup.city}, #{meetup.state} #{meetup.zip}" %>

<h3>Date & Time</h3>
<p><strong>Starts At</strong> <%= meetup.start_at %></p>
<p><strong>Ends At</strong> <%= meetup.ends_at %></p>

<h3>Description</h3>
<p><%= meetup.description %></p>
</article>

<div class="attend-info">
	<%= render :partial => 'attend', locals: { meetup: meetup} %>
</div>

</section>
<hr>
<% if can? :manage, meetup %>
  <p class="actions">
    <%= link_to 'Edit', edit_meetup_path(meetup), class: 'btn btn-primary' %>
    <%= link_to 'Cancel', meetups_path, class: 'btn' %>
  </p>
<% end %>