config/routes.rb
Meetme::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  resources :avatars, only: [:edit, :update, :destroy]

  post    'meetups/:meetup_id/attend' => 'attends#create', as: 'attend_meetup'
  delete 'meetups/:meetup_id/attend' => 'attends#destroy'

  get  'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get  'logout' => 'sessions#destroy', as: 'logout'

  get  'register' => 'users#new', as: 'register'
  post  'register' => 'users#create'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :hash_password

  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true, presence: {on: :create}

  has_and_belongs_to_many :meetups, join_table: 'attends'
  has_one :profile, dependent: :destroy

  delegate :name, to: :profile, allow_nil: true
  delegate :age, to: :profile, allow_nil: true

  def hash_password
    if password_changed?
      write_attribute(:password, BCrypt::Password.create(password))
    end
  end

  def attend_for_meetup(meetup)
    meetups << meetup unless attends_for_meetup?(meetup)
  end

  def cancel_attend_for_meetup(meetup)
    meetups.delete meetup if attends_for_meetup?(meetup)
  end

  def attends_for_meetup?(meetup)
    meetups.include? meetup
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource only: [:edit, :update, :destroy]
  before_filter :authenticate!, only: [:edit, :update, :destroy]
  
  def index
    @users = User.includes(:profile).page(params[:page])
  end

  def new
    @user = User.new
    @profile = Profile.new
  end

  def create
    @user = User.new user_params
    @profile = Profile.new profile_params

    if @user.valid? && @profile.valid?
      @user.profile = @profile 
      @user.save

      user_session.start_session @user 
      flash[:success] = "Acount created and logged in successfully"
      redirect_to root_url
    else
      @profile.valid?
      flash[:error] = "There was an problem."
      render :new
    end
  end


  def edit
    @profile = @user.profile || Profile.new
  end

  def update
    @user.build_profile 
    @user.assign_attributes user_params
    @user.profile.assign_attributes profile_params

    if @user.valid? && @user.profile.valid?
      @user.save
      flash[:success] = "Updated the profile succses"
      redirect_to users_path
    else
      @user.profile.valid?
      @profile = @user.profile

      flash[:error] = "There was a problem"
      redirect_to 
      render :edit
    end
  end

  def destroy
    logout = current_user.id == user.id
    @user.destroy
    user_session.destroy_session if logout


    flash[:success] = "The account has been deleted"
    redirect_to users_path
  end

  private

  def user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :profile)
  end

  def profile_params
    params.require(:profile).permit(:name, :age, :avatar_file_name)
  end

end

app/views/users/edit.html.erb
<div class="row-fluid">
  <div class="span6">
    <%= form_for @user do |f| %>
      <%= fields_for @profile do |field| %>
        <p>
          <%= field.label :name %>
          <%= field.text_field :name %>
        </p>
        <p>
          <%= field.label :age %>
          <%= field.text_field :age %>
        </p>
      <% end %>
      <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </p>
      <p class="actions">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', root_url, class: 'btn' %>
      </p>
    <% end %>
  </div>
  <div class="span6">
    <p>
      <%= image_tag @user.profile.avatar.url, alt: @user.email %>
      <%= link_to 'Change Avatar', edit_avatar_path(@user), class: 'btn btn-success' %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<div class="users">
  <h1>Users</h1>
  <% if @users.present? %>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Email</th>
          <th>Name</th>
          <th>Age</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.profile.avatar.url, class: 'avatar-thumb' %></td>
            <td><%= user.email %></td>
            <td><%= user.name %></td>
            <td><%= user.age %></td>
            <td>
              <div class="btn-group">
                <% if can? :manage, user %>
                  <%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(user), class: 'btn' %>
                  <%= link_to '<i class="icon-trash"></i>'.html_safe, user, class: 'btn btn-danger', method: 'delete' %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>There are no users for this users group!</p>
  <% end %>

  <% unless current_user %>
    <p><%= link_to 'Register for our User Group!', register_path, class: 'btn btn-primary' %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? || @profile.errors.any? %>
  <div class="alert alert-error">
    <% [@profile, @user].each do |resource| %>
      <% resource.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <%= fields_for @profile do |field| %>
    <p>
      <%= field.label :name %>
      <%= field.text_field :name %>
    </p>
    <p>
      <%= field.label :age %>
      <%= field.text_field :age %>
    </p>
  <% end %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', root_url, class: 'btn' %>
  </p>
<% end %>