config/routes.rb
Meetme::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  resources :avatars, only: [:edit, :update, :destroy]

  post    'meetups/:meetup_id/attend' => 'attends#create', as: 'attend_meetup'
  delete 'meetups/:meetup_id/attend' => 'attends#destroy'

  get  'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get  'logout' => 'sessions#destroy', as: 'logout'

  get  'register' => 'users#new', as: 'register'
  post  'register' => 'users#create'

  root 'home#index'

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_filter :authenticate!
  before_filter :user

  def edit
  end

  def update
    if params[:profile][:avatar].present?
      if user.profile.update_attributes profile_params
        flash[:success] = "File uploaded successfully"
      else
        flash[:error] = "Something went wrong with the upload"
      end
    else
      flash[:error] = "No file provided"
    end

    redirect_to edit_avatar_path(user)
  end

  def destroy
    if user.profile.avatar?
      user.profile.avatar = nil
      user.profile.save
      flash[:success] = "File deleted successfully"
    else
      flash[:success] = "There was no avatar to delete"
    end

    redirect_to edit_avatar_path(user)
  end

  private

  def user
    @user ||= User.find params[:id]
    authorize! :manage, @user
  end

  private
  def profile_params
    params.require(:profile).permit(:name, :age, :avatar)
  end


end

app/views/avatars/edit.html.erb
<div class="avatar-form">
  <%= form_for @user.profile, url: avatar_path(@user), html: { multipart: true } do |f| %>
    <p>
      <%= f.label :avatar, 'Upload New Avatar' %>
      <%= f.file_field :avatar %>
    </p>
    <p class="actions">
      <%= f.submit 'Upload Avatar', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', edit_user_path(@user), class: 'btn' %>
    </p>
  <% end %>

  <hr>

  <% if @user.profile.avatar? %>
    <%= image_tag @user.profile.avatar.url, class: 'avatar-thumb' %>
    <%= link_to 'Delete My Avatar', avatar_path(@user), class: 'btn btn-danger', method: 'delete' %>
  <% else %>
    <p>No Avatar Set!</p>
  <% end %>
</div>