config/routes.rb
Meetme::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :meetups
  resources :avatars, only: [:edit, :update, :destroy]

  post    'meetups/:meetup_id/attend' => 'attends#create', as: 'attend_meetup'
  delete 'meetups/:meetup_id/attend' => 'attends#destroy'

  get  'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get  'logout' => 'sessions#destroy', as: 'logout'

  get  'register' => 'users#new', as: 'register'
  post  'register' => 'users#create'

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Users Group</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <style type="text/css">
    body {
      padding-top: 60px;
      padding-bottom: 40px;
    }
    .sidebar-nav {
      padding: 9px 0;
    }
  </style>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Home', root_path, class: 'brand' %>
        <div class="nav-collapse collapse">
          <p class="navbar-text pull-right">
            <% if current_user %>
              <%= link_to "Welcome, #{current_user.email}", edit_user_path(current_user), class: 'navbar-link' %> |
              <%= link_to 'Logout', logout_path %>
            <% else %>
              <%= link_to 'Login', login_path %> |
              <%= link_to 'Register', register_path %>
            <% end %>
          </p>
          <ul class="nav">
            <li class="<%= params[:controller] == 'users'   && 'active' %>"><%= link_to 'Users', users_path %></li>
            <li class="<%= params[:controller] == 'meetups' && 'active' %>"><%= link_to 'Meetups', meetups_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <%= render 'shared/notifications' %>
        <%= yield %>
      </div><!--/span-->
    </div><!--/row-->

    <hr>

    <footer>
    <p>&copy; Company 2014</p>
    </footer>

  </div><!--/.fluid-container-->
</body>
</html>